language: node_js

node_js:
    - 14.16.1
    - 15.14.0

branches:
    only:
        - main
        - dev

env:
    global:
        - NODE_ENV='production'
        - BASE_URL='./'

cache: npm

script:
    - pwd
    - ls
    - ls ~

