language: node.js

node_js:
    - 14.16.1
    - 15.14.0

branches:
    only:
        - main
        - dev

env:
    global:
        - NODE_ENV='production'
        - BASE_URL='./'

cache: npm

before_script:
    - npm ci

script:
    - npm run build

