name: CI
on:
    pull_request:
        types:
            - opened
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
        strategy:
            matrix:
                node-version: ['12.x']
        steps:
            - name: Checkout
            - uses: actions/checkout@v2
              with:
                  ref: ${{github.event.pull_request.head.ref}}
            - name: install and build & push the built app to the main branch
              run: |
                  npm ci
                  npm run build
                  git config --global user.name "tyautyau56"
                  git config --global user.email "tyautyau56@gmail.com"
                  git add .
                  git commit -m 'app build & push main branch!' && git push ${REPO} HEAD:${{github.event.pull_request.head.ref}} || true
                  git pull
                  git push origin main
              env:
                  CI: true
            - name: merge pull request
              uses: actions/github-script@0.4.0
              with:
                  github-token: ${{select.GITHUB_TOKEN}}
                  script: |
                      github.pulls.merge({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      pull_number: context.payload.pull._request.number
                      })
