name: CI
on:
    push:
        branches: [ main ]
        paths:
            - './src/**/*.{js,scss,json,css,ts,tsx,jsx}'
    pull_request:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ['12.x']
        steps:
            - uses: actions/checkout@v2
            - name: install and build
              run: |
                  npm ci
                  npm run build
              env:
                  CI: true
            - name: push the built app to the main branch
              run: |
                  git config --local user.name "tyautyau56"
                  git config --local user.email "tyautyau56@gmail.com"
                  git add .
                  git commit -m "app build & push main branch!" -a
                  git pull origin main
                  git push origin main
